<Project Sdk="Microsoft.NET.Sdk.Worker">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>disable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<WarningsAsErrors></WarningsAsErrors>
		<NoWarn>8600;8602;8603;8618;8625</NoWarn>
		<UserSecretsId>dotnet-POSPRA.Worker-6ed6f5a6-a19a-4724-9b76-89df9951af05</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Hangfire.SqlServer" Version="1.8.21" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.9" />
		<PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="9.0.9" />
		<ProjectReference Include="..\Pos.Api\Pos.Local.Api.csproj" />
		<ProjectReference Include="..\Pos.Application\Pos.Application.csproj" />
		<ProjectReference Include="..\Pos.Infrastructure\Pos.Infrastructure.csproj" />
		<ProjectReference Include="..\POSPRA.SecurityEncryption\POSPRA.SecurityEncryption.csproj" />
	</ItemGroup>
</Project>
