<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net9.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>
		<ApplicationManifest>app.manifest</ApplicationManifest>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="Updater-Version.config" />
	</ItemGroup>

	<ItemGroup>
	  <Content Include="Updater-Version.config">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>

	<!-- ✅ Add this block -->
	<ItemGroup>
		<PackageReference Include="System.ServiceProcess.ServiceController" Version="9.0.0" />
	</ItemGroup>

</Project>
