<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows7.0</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>
		<ApplicationManifest>app.manifest</ApplicationManifest>
	</PropertyGroup>

	<ItemGroup>
	  <AdditionalFiles Remove="app1.manifest" />
	</ItemGroup>

	<!-- ✅ Add this block -->
	<ItemGroup>
		<PackageReference Include="System.ServiceProcess.ServiceController" Version="9.0.10" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\Pos.Application\Pos.Application.csproj" />
	  <ProjectReference Include="..\Pos.SecurityEncryption\Pos.SecurityEncryption.csproj" />
	</ItemGroup>

</Project>
