<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="15.0.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Portable.BouncyCastle" Version="1.9.0" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="9.0.8" />
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="9.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\POSPRA.Domain\POSPRA.Domain.csproj" />
    <ProjectReference Include="..\POSPRA.DTOs\POSPRA.DTOs.csproj" />
    <ProjectReference Include="..\POSPRA.Repositories\POSPRA.Repositories.csproj" />
  </ItemGroup>

</Project>
