<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.17763.0</TargetFramework>
    <RootNamespace>Pos.WinFormsUI</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app1.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="app-version.txt" />
    <None Remove="Reports\InvoiceReport.rdlc" />
    <None Remove="Reports\ReportDataSet.xsd" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="app-version.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Reports\InvoiceReport.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Reports\ReportDataSet.xsd">
      <Generator>MSDataSetGenerator</Generator>
      <LastGenOutput>ReportDataSet.Designer.cs</LastGenOutput>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="CommunityToolkit.WinUI.Notifications" Version="7.1.2" />
    <PackageReference Include="Guna.UI2.WinForms" Version="2.0.4.7" />
    <PackageReference Include="LiveCharts.WinForms" Version="0.9.7.1" />
    <PackageReference Include="Microsoft.AspNetCore.Hosting" Version="2.3.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.9" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.9" />
    <PackageReference Include="Microsoft.SqlServer.TransactSql.ScriptDom" Version="170.128.0" />
    <PackageReference Include="QRCoder" Version="1.7.0" />
    <PackageReference Include="ReportViewerCore.NETCore" Version="15.1.26" />
    <PackageReference Include="ReportViewerCore.WinForms" Version="15.1.26" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Pos.Application\Pos.Application.csproj" />
    <ProjectReference Include="..\Pos.BATTO_EXE\Pos.BATTO_EXE.csproj" />
    <ProjectReference Include="..\Pos.Cloud.Api\Pos.Cloud.Api.csproj" />
    <ProjectReference Include="..\Pos.Domain\Pos.Domain.csproj" />
    <ProjectReference Include="..\Pos.Infrastructure\Pos.Infrastructure.csproj" />
    <ProjectReference Include="..\Pos.Local.Api\Pos.Local.Api.csproj" />
    <ProjectReference Include="..\Pos.SecurityEncryption\Pos.SecurityEncryption.csproj" />
    <ProjectReference Include="..\Pos.SetupUI\Pos.SetupUI.csproj" />
    <ProjectReference Include="..\Pos.Updater\Pos.Updater.csproj" />
    <ProjectReference Include="..\Pos.Worker\Pos.Worker.csproj" />
	<PackageReference Include="System.Configuration.ConfigurationManager" Version="9.0.10" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="CommunityToolkit.WinUI.Notifications">
      <HintPath>bin\Debug\net9.0-windows10.0.17763.0\Microsoft.CommunityToolkit.WinUI.Notifications.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Reports\ReportDataSet.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ReportDataSet.xsd</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>